# Slightly adapted from docker4drupal.
# See https://docker4drupal.readthedocs.io/en/latest/
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      # See all available mariadb variables at https://github.com/wodby/mariadb.
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      # Any database dump in /mariadb-init will be loaded when the container is initiated.
      - ./mariadb-init:/docker-entrypoint-initdb.d

  php:
    image: wodby/drupal-php:7.1-3.0.0
    environment:
      # See all available PHP variables at https://github.com/wodby/php.
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      # Pass through environment variables from .env
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      PHP_TIMEZONE: "America/Chicago"
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh:/home/www-data/.ssh
      - ~/.drush/site-aliases:/home/www-data/.drush/site-aliases

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.1
    depends_on:
      - php
    environment:
      # See all available NGINX variables at https://github.com/wodby/php.
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.docker.localhost"
    volumes:
      - ./:/var/www/html:cached

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - "traefik.frontend.rule=Host:mailhog.${COMPOSE_PROJECT_NAME}.docker.localhost"

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - "traefik.frontend.rule=Host:portainer.${COMPOSE_PROJECT_NAME}.docker.localhost"

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/ssl/certs:/certs/
    ports:
      - '4443:43'
